export const Users=[
    {
        id:1,
        ProfilePicture:"assets/person/first.jpeg",
        username:"Shubham kumar",
    },
    {
        id:2,
        ProfilePicture:"assets/person/second.jpeg",
        username:"Akshay kumar",
    },
    {
        id:3,
        ProfilePicture:"assets/person/third.jpeg",
        username:"Aman kumar",
    },
    {
        id:4,
        ProfilePicture:"assets/person/fourth.jpeg",
        username:"Raj yadav",
    },
    {
        id:5,
        ProfilePicture:"assets/person/fifth.jpeg",
        username:"sonu Roy",
    },
    {
        id:6,
        ProfilePicture:"assets/person/six.jpeg",
        username:"Amit kumar",
    },
    {
        id:7,
        ProfilePicture:"assets/person/seven.jpeg",
        username:"Karan kumar",
    },
    {
        id:8,
        ProfilePicture:"assets/person/eight.jpeg",
        username:"Omparkash kumar",
    },
    {
        id:9,
        ProfilePicture:"assets/person/nine.jpeg",
        username:"Mohan kumar",
    },
    {
        id:10,
        ProfilePicture:"assets/person/six.jpeg",
        username:"Vivek kumar",
    },

]

export const Posts=[
    {
        id:1,
        desc:"Love for all , Hatred for none",
        photo:"assets/post/first.jpeg",
        date:"5 min ago",
        userId:1,
        like:32,
        comment:9,
    },
    {
        id:2,
        desc:"Honesty is the best.",
        photo:"assets/post/second.jpeg",
        date:"45 min ago",
        userId:2,
        like:42,
        comment:22,
    },
    {
        id:3,
        desc:"Hello world welcome",
        photo:"assets/post/third.jpeg",
        date:"5 min ago",
        userId:3,
        like:68,
        comment:19,
    },
    {
        id:4,
        desc:"Happy Dewali ",
        photo:"assets/post/fourth.jpeg",
        date:"45 min ago",
        userId:4,
        like:73,
        comment:43,
    },
    {
        id:5,
        desc:"Every one is happy , i wish",
        photo:"assets/post/ten.jpeg",
        date:"47 min ago",
        userId:5,
        like:53,
        comment:27,
    },
    {
        id:6,
        desc:"Love for all , Hatred for none",
        photo:"assets/post/six.jpeg",
        date:"25 min ago",
        userId:6,
        like:232,
        comment:39,
    },
    {
        id:7,
        desc:"Love  for all",
        photo:"assets/post/seven.jpeg",
        date:"5 min ago",
        userId:7,
        like:323,
        comment:39,
    },
    {
        id:8,
        desc:"Make the world happy",
        photo:"assets/post/first.jpeg",
        date:"45 min ago",
        userId:8,
        like:62,
        comment:38,
    },
    {
        id:9,
        desc:"Explore Everthings !! ",
        photo:"assets/post/third.jpeg",
        date:"45 min ago",
        userId:9,
        like:142,
        comment:38,
    },
    {
        id:10,
        desc:"Welcome my love ",
        photo:"assets/post/seven.jpeg",
        date:"45 min ago",
        userId:10,
        like:352,
        comment:38,
    },

]